---
layout: single
title: |-
  Buying reputation as a signal of quality:
  Evidence from an online marketplace
date: 2026-04-04 15:58 +0900
categories:
  - Paper Review
tags:
  - review
  - online-platform
---

**by Lingfang Li, Steven Tadelis, and Xiaolan Zhous** *(The RAND Journal of Economics, 2020)*

---

> **Abstract**
> *Seller reputation, generated by buyer feedback, is critical to fostering trust in online marketplaces. Marketplaces or sellers may choose to compensate buyers for providing feedback. Signaling theory predicts that only sellers of high-quality products will reward buyers for truthful feedback, especially when a product lacks any feedback and when the seller is not established. We confirm these hypotheses using Taobao's reward-for-feedback mechanism. High-quality products, especially without established feedback, are chosen for feedback rewards, which cause sales to increase by 36%. Marketplaces and consumers can therefore benefit from allowing sellers to buy feedback and signal their high-quality products in the process.*

## **1. Summary**

This paper studies whether sellers can “buy” reputation in a way that credibly signals product quality. Using proprietary data from Taobao’s reward-for-feedback (RFF) mechanism, the authors argue that offering buyers a rebate for leaving **informative** feedback can work like a signal: high-quality sellers are more willing to pay for feedback because they expect positive and detailed reviews, while low-quality sellers have less incentive to do so. Consistent with this signaling logic, sellers are more likely to adopt RFF for high-quality items, especially for cold-start products with no established feedback, and less likely to rely on it when the seller already has a strong reputation.
